
name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@uglier-and-somehow-prettier
    secrets: inherit
    with:
      timeout: 150
